name: Terraform Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight, adjust as needed

jobs:
  terraform-destroy:
    name: Terraform Destroy AWS
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'us-east-1'
      TF_VERSION: '1.12.1'

    steps:
    - name: 'checkout github responstory'
      uses: actions/checkout@v4

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: ${{ env.TF_VERSION }}

    - name: Terraform Init
      run: cd iac_using_terraform && terraform init
    
    - name: Terraform Plan Destroy
      run: cd iac_using_terraform && terraform plan -destroy -out=tfplan-destroy

    - name: Terraform Apply Destroy
      run: cd iac_using_terraform && terraform apply -auto-approve tfplan-destroy
     